CREATE DATABASE IF NOT EXISTS watermark_db;
USE watermark_db;

CREATE TABLE IF NOT EXISTS Users (
  id INTEGER NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  isVerified BOOLEAN DEFAULT false,
  verificationToken VARCHAR(255),
  monthlyUsage INTEGER DEFAULT 0,
  monthlyLimit INTEGER DEFAULT 20,
  lastUsageReset DATETIME DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS conversion_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INTEGER NOT NULL,
    ipAddress VARCHAR(255),
    userAgent VARCHAR(255),
    fileSize INT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS conversion_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    logId INT NOT NULL,
    processedPath VARCHAR(255) NOT NULL,
    originalPath VARCHAR(255) NOT NULL,
    FOREIGN KEY (logId) REFERENCES conversion_logs(id) ON DELETE CASCADE
);
